"""Administrative research pipeline foundations."""

from .artifacts import ArtifactStore, ProtectedArtifactScope
from .config import PipelineConfig, load_pipeline_config
from .formal_gc import FormalGcResult, collect_unreferenced_formal_resources
from .ingestion import BatchIngestor, IngestionResult, IngestionService, UploadIngestion, UploadPart
from .matching import BibTeXMatcher, BibtexMatcher, MatchResult
from .publication import (
    FormalStore,
    LanceDBIndexer,
    LocalFormalStore,
    MirroredFormalStore,
    PublicationBundle,
    PublicationCancelled,
    PublicationConflict,
    PublicationError,
    PublicationResource,
    PublicationResult,
    PublicationWorker,
    PublicationWorkerResult,
    WebDavFormalStore,
    build_bundle_from_preview,
    build_publication_bundle,
    build_publication_bundle_from_manifest,
    publication_manifest,
    publish_bundle,
    queue_publication,
    validate_vector_index,
)
from .state import (
    ALL_STEP_NAMES,
    BatchMatchConflict,
    JOB_STATUSES,
    PROCESSING_STEP_NAMES,
    STEP_NAMES,
    Lease,
    LeaseGuard,
    PipelineState,
    PreviewGenerationConflict,
)

__all__ = [
    "ArtifactStore",
    "ProtectedArtifactScope",
    "JOB_STATUSES",
    "ALL_STEP_NAMES",
    "BatchMatchConflict",
    "PreviewGenerationConflict",
    "Lease",
    "LeaseGuard",
    "PipelineConfig",
    "PipelineState",
    "STEP_NAMES",
    "PROCESSING_STEP_NAMES",
    "load_pipeline_config",
    "FormalGcResult",
    "collect_unreferenced_formal_resources",
    "BatchIngestor",
    "IngestionResult",
    "UploadPart",
    "IngestionService",
    "UploadIngestion",
    "BibTeXMatcher",
    "BibtexMatcher",
    "MatchResult",
    "FormalStore",
    "LanceDBIndexer",
    "LocalFormalStore",
    "MirroredFormalStore",
    "PublicationBundle",
    "PublicationCancelled",
    "PublicationConflict",
    "PublicationError",
    "PublicationResource",
    "PublicationResult",
    "PublicationWorker",
    "PublicationWorkerResult",
    "WebDavFormalStore",
    "build_bundle_from_preview",
    "build_publication_bundle",
    "build_publication_bundle_from_manifest",
    "publication_manifest",
    "publish_bundle",
    "queue_publication",
    "validate_vector_index",
]

from .worker import (
    FIXED_STEP_SEQUENCE,
    FIXED_STEPS,
    PROCESSING_STEPS,
    PipelineAdapters,
    PipelineWorker,
    PreviewArtifacts,
    ProductionAdapters,
    WorkerResult,
    build_production_adapters,
    run_worker,
    run_production_worker,
    run_processing_worker,
    STEP_SEQUENCE,
    Worker,
    worker_entrypoint,
)
from .api import create_admin_pipeline_app, create_pipeline_admin_app
from .runtime import (
    PipelineEnvironment,
    WorkerLoopResult,
    build_publication_bundle_from_state,
    run_production_worker_forever,
    run_worker_until_stopped,
    resolve_snapshot_db,
    validate_pipeline_mounts,
    validate_pipeline_environment,
)

__all__ += [
    "FIXED_STEP_SEQUENCE",
    "FIXED_STEPS",
    "PROCESSING_STEPS",
    "PipelineAdapters",
    "PipelineWorker",
    "Worker",
    "PreviewArtifacts",
    "ProductionAdapters",
    "WorkerResult",
    "build_production_adapters",
    "run_worker",
    "run_production_worker",
    "run_processing_worker",
    "STEP_SEQUENCE",
    "worker_entrypoint",
    "create_pipeline_admin_app",
    "create_admin_pipeline_app",
    "PipelineEnvironment",
    "WorkerLoopResult",
    "build_publication_bundle_from_state",
    "run_production_worker_forever",
    "run_worker_until_stopped",
    "resolve_snapshot_db",
    "validate_pipeline_mounts",
    "validate_pipeline_environment",
]
